allowBuilds:
  sharp: true
  unrs-resolver: true
  "@prisma/engines": true
  prisma: true
  esbuild: true
  '@parcel/watcher': false
  '@swc/core': false
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@prisma/engines"
  - prisma
